eureka:
  instance:
    prefer-ip-address: true #ip of server will be used to register
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka  
